export const QUEUE_NAMES = {
  AUTH: 'auth_service_queue',
  USER: 'user_service_queue',
  LISTINGS: 'listings_service_queue',
  BILLING: 'billing_service_queue',
  MESSAGING: 'messaging_service_queue',
  NOTIFICATION: 'notification_service_queue',
  SEARCH: 'search_service_queue',
  ALGOLIA: 'algolia_service_queue',
  CHECKOUT: 'checkout_service_queue',
  CONTRACTS: 'contracts_service_queue',
  EARNINGS: 'earnings_service_queue',
  FAVORITES: 'favorites_service_queue',
  INVITATIONS: 'invitations_service_queue',
  PAYOUT: 'payout_service_queue',
  PORTFOLIO: 'portfolio_service_queue',
  TRANSACTION: 'transaction_service_queue',
  TIME_TRACKING: 'time_tracking_service_queue',
  CONTENT_MODERATION: 'content_moderation_service_queue',
  AUTOCOMPLETE: 'autocomplete_service_queue',
  SUGGESTIONS: 'suggestions_service_queue',
  AFFILIATE_REFERRAL: 'affiliate_referral_service_queue',
  ADMIN: 'admin_service_queue',
} as const;

export const EVENTS = {
  USER_CREATED: 'user.created',
  USER_UPDATED: 'user.updated',
  AUTH_LOGIN: 'auth.login',
  AUTH_LOGOUT: 'auth.logout',
  LISTING_CREATED: 'listing.created',
  LISTING_UPDATED: 'listing.updated',
  CONTRACT_GROUP_CREATED: 'contract.group.created',
  CONTRACT_ACTIVATED: 'contract.activated',
  CONTRACT_GROUP_ACTIVATED: 'contract.group.activated',
  CONTRACT_ENDED: 'contract.ended',
  CONTRACT_GROUP_ENDED: 'contract.group.ended',
  CONTRACT_CANCELED: 'contract.canceled',
  CONTRACT_DISPUTED: 'contract.disputed',
  CONTRACT_COMPLETED: 'contract.completed',
  TRANSACTION_CREATED: 'transaction.created',
  PAYOUT_COMPLETED: 'payout.completed',
  EARNINGS_UPDATED: 'earnings.balance.updated',
  NOTIFICATION_SEND: 'notification.send',
  MESSAGE_SENT: 'message.sent',
} as const;
